### ISSUE TITLE
Поддержка 7.7-7.9 ElasticSearch

### ISSUE THREAD

**Issue by giardo911** [anti-social/jmorphy2#23]
Подскажите, планируется поддержка 7.7 + версий Elastic?

**Comment by anti-social** [comment]
- [7.7.1](https://bintray.com/evo/elasticsearch/download_file?file_path=analysis-jmorphy2-0.2.2-es7.7.1.zip)
- [7.8.1](https://bintray.com/evo/elasticsearch/download_file?file_path=analysis-jmorphy2-0.2.2-es7.8.1.zip)
- [7.9.2](https://bintray.com/evo/elasticsearch/download_file?file_path=analysis-jmorphy2-0.2.2-es7.9.2.zip)

**Comment by anti-social** [comment]
Fixed.
