### ISSUE TITLE
Elasticsearch не видит фильтр jmorphy2_stemmer

### ISSUE THREAD

**Issue by EgorLakomkin** [anti-social/jmorphy2#3]
Может я неверно использую плагин, пробую вот такой конфиг для анализатора:

```
"rus_analyzer": {
                                    "type": "custom",
                                     "tokenizer": "standard",
                                     "filter": ["lowercase", "jmorphy2_stemmer"]
                           }
В результате
```

IllegalArgumentException[Custom Analyzer [rus_analyzer] failed to find filter under name [jmorphy2_stemmer]]; ","status":400}

При загрузке плагин elastic вроде видит:  loaded [analysis-jmorphy2, ... ].

Как правильно развернуть библиотеку на elasticsearch? Кстати куда нужно копировать словари?

**Comment by anti-social** [comment]
Добавил в readme инструкцию для эластика. Отпишись, получилось ли.

**Comment by EgorLakomkin** [comment]
Спасибо! Все заработало!

**Comment by vesnindev** [comment]
Здравствуйте. Такая же ошибка:

` Elasticsearch\Common\Exceptions\BadRequest400Exception  : {"error":{"root_cause":[{"type":"illegal_argument_exception","reason":"Unknown filter type [jmorphy2_stemmer] for [jmorphy2_russian]"}],"type":"illegal_argument_exception","reason":"Unknown filter type [jmorphy2_stemmer] for [jmorphy2_russian]"},"status":400}`


, делаю по инструкции:

```
jmorphy2_russian:
          type: jmorphy2_stemmer
          name: ru

```

Версия ES: 7.9.3

**Comment by anti-social** [comment]
Плагин установлен и загружается при старте эластика? В `stdout` должна быть строка:

```
loaded plugin [analysis-jmorphy2]
```
