### ISSUE TITLE
Bintray url retrurns 404

### ISSUE THREAD

**Issue by DenisNovac** [anti-social/jmorphy2#30]
URL from main page:

https://bintray.com/evo/elasticsearch/download_file?file_path=analysis-jmorphy2-0.2.2-es7.11.2.zip

**Comment by DenisNovac** [comment]
It seems they are closing the service:
> With regards to your query regarding unable to download the file from the reported account, please be informed that as part of the Bintray sunset plan, we have blocked all the OSS Bintray accounts, and download from the OSS Bintray account is forbidden.
>For more information, we would request you to refer to the below link:
https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/

**Comment by anti-social** [comment]
Now Elasticsearch plugin builds are here inside releases.
