### ISSUE TITLE
Поддержка более свежих версий Elasticsearch

### ISSUE THREAD

**Issue by lzakharov** [anti-social/jmorphy2#34]
Приветствую!
Есть ли в планах поддержка более свежих версий Elasticsearch (> 7.13)?

**Comment by ykweb** [comment]
Плюсую. Очень хотелось бы установить на свежие версии эластика.
Как можно помочь?

**Comment by nariman9119** [comment]
@anti-social подскажи пожалуйста)

**Comment by anti-social** [comment]
Насколько я понимаю, данньій плагин используется в основном в РФ. Я не хочу чтобьі мой софт использовался на территории страньі не уважающей суверенитет соседних стран и пьітающейся оккупировать их, так как российские компании будут платить налоги на которьіе будет финансироваться война в Украине. Поєтому на данньій момент публичная разработка приостановлена.

Возможно я изменю лицензию, чтобьі явно запретить использование данной библиотеки на територии РФ и тогда публичная разработка будет возобновлена.

Если кто-либо хочет использовать библиотеку на территории других стран, то пока что можно написать мне лично и я дам доступ к закрьітому репозиторию.

**Comment by ykweb** [comment]
@anti-social Здравствуйте. Не нашел ваших контактов и способа написать вам в личные сообщения.
Вашу библиотеку используют не только в РФ, но и в других странах СНГ, таких как Казахстан =)
