### ISSUE TITLE
Разбор несловарного слова "аминовен"

### ISSUE THREAD

**Issue by EgorLakomkin** [anti-social/jmorphy2#4]
Разбирается с леммой "амин", отбрасывая суффикс "овен". Насколько я понимаю необходимо в словарь opencorpora добавить информацию о парадигме, в которой возможен вариант, когда словоформа "аминовен" в именительном падеже?

**Comment by anti-social** [comment]
Это как раз словарное слово. Это можно проверить с помощью pymorphy2. 

"NOUN,anim,femn,Patr plur,gent" - это женское отчество в множественном числе родительном падеже от имени Амин.

**Comment by EgorLakomkin** [comment]
Я неправильно выразился. У этого слова есть еще одно значение, которого нет в словаре - лекарство "аминовен" у которого лемма "аминовен".

**Comment by anti-social** [comment]
Я не думаю, что стоит добавлять в словарь названия всех лекарств. Лучше спросить об этом у сообщества Opencorpora.

Можно добавить перед стеммером фильтр `synonym` и заменять все возможные формы на каноническую "аминовен". И затем фильтр `keep`, который отключит стеммер для данного токена. Фактически получишь такую себе базу по названиям лекарств.

Или можешь сделать свою версию словаря и добавить в него все нужные тебе парадигмы.

**Comment by anti-social** [comment]
Думаю к самой библиотеке это не относится, так что закрываю.
