### ISSUE TITLE
Работа с UnknownWordUnit

### ISSUE THREAD

**Issue by mikhail-barg** [anti-social/jmorphy2#5]
У меня сложилось представление, что jmorphy не умеет склонять несловарные слова. 

К примеру: `morph.parse("няшка")` возвращает 

```
<ParsedWord: "няшка", "UNKN", "няшка", "няшка", 1,000000, class net.uaprom.jmorphy2.AnalyzerUnit$UnknownWordUnit>
```

с единственным элементом в `getLexeme()` и невозможностью склонять.

В то время как pymoprhy2 на `morph.parse(u'няшка')` отвечает

```
[Parse(word=u'няшка', tag=OpencorporaTag('NOUN,inan,femn sing,nomn'), normal_form=u'няшка', score=1.0, methods_stack=((<FakeDictionary>, u'няшка', 9, 0), (<KnownSuffixAnalyzer>, u'няшка')))]
```

а `morph.parse(u'няшка')[0].inflect({'gent'}).word` выдает ожидаемое `u'няшки'`.

Это ожидаемое поведение со стороны jmorphy? Или я просто не умею его готовить?

**Comment by anti-social** [comment]
Да, нахождение слова по известному суффиксу не реализовано. Склонение также не реализовано. Мне просто была нужна только нормальная форма слова для стемминга в Solr и Elasticsearch.

Постараюсь в ближайшее время довести до ума.

**Comment by anti-social** [comment]
https://github.com/anti-social/jmorphy2/commit/8dfc03dcc22a603045d30a020f46c0caf9ac604e#diff-0c6c4b5cd2c87b5d3355162634a05297R82
